#ifndef REMVIEWPLUGIN_GLOBAL_H
#define REMVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REMVIEWPLUGIN_LIBRARY)
#  define REMVIEWPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REMVIEWPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REMVIEWPLUGIN_GLOBAL_H
